### ISSUE TITLE
bootconfig container

### ISSUE THREAD

**Issue by tiagolobocastro** [nats-io/k8s#207]
Hi,

May I ask what the bootconfig container is used for? It mentions external ips, so does it mean it's only needed if we want to connect a remote nats cluster via a leaf or something like that?

Thanks

**Comment by wallyqs** [comment]
It for when you want to use something like external-dns or you want to be able to connect to the public ip of each one of the nats servers.  For example at Synadia we have a global NATS service running at:

```
telnet connect.ngs.global 4222
Trying 34.222.173.171...
Connected to connect.ngs.global.
Escape character is '^]'.
INFO {"server_id":"NALZ46TWH3HWITWAWJSHKVLQHDLWS334TGK2UJ7XOC5UZMNISCSZSYVD","server_name":"aws-uswest2_ngs-nats-green-1","version":"2.2.0-beta.96","proto":1,"git_commit":"48d9e1cdb04d7f8d1905f38842dab639fd3d1fe2","go":"go1.15.8","host":"34.222.173.171","port":4222,"headers":true,"auth_required":true,"tls_required":true,"max_payload":1048576,"client_id":294,"client_ip":"174.194.200.37","nonce":"1YWyYkTUBVLJdfM","cluster":"aws-uswest2","connect_urls":["34.222.173.171:4222","52.38.30.12:4222","54.188.253.29:4222"]} 
```

In the `connect_urls` you can see that those are the public ips of each one of the NATS Server nodes running in AWS:

```
nslookup connect.ngs.global
Server:		172.20.10.1
Address:	172.20.10.1#53

Non-authoritative answer:
Name:	connect.ngs.global
Address: 34.222.173.171
Name:	connect.ngs.global
Address: 54.188.253.29
Name:	connect.ngs.global
Address: 52.38.30.12
```

When combining that with a nodeport + external-dns, you are able to advertise those ips dynamically:
https://github.com/nats-io/kubecon2020#create-nodeport-service-to-create-a-records-for-each-server

The reason why the container exists though is because there is no way in Kubernetes to know the public ip from a node (`KUBERNETES_NODE_PUBLIC_IP`), so this initializer container makes a query to the Kubernetes API so that the NATS Server configuration is able include that as the `client_advertise` instead of the default private ip of the k8s network...

**Comment by tiagolobocastro** [comment]
Got it, thank you so much!
