### ISSUE TITLE
Issue with PDB selecting version. 

### ISSUE THREAD

**Issue by BenCoughlan15** [nats-io/k8s#473]
Hi, 

i'm using GKE - kube version  1.20.12-gke.1500

```
> kubectl api-versions | grep policy
policy/v1beta1
```

https://github.com/nats-io/k8s/blob/7b96ec72e216cefff525e61c11be6a0c39f3ae57/helm/charts/nats/templates/pdb.yaml#L3

This means I can't use the PDB, because it expects that API version to be there. 

Can we allow for a way to set this explicitly from the value files?

**Comment by caleblloyd** [comment]
The way it was written is so that the statement default will default to:

` apiVersion: policy/v1beta1`

That's what the `ternary` operator is for - if `.Capabilities.APIVersions.Has "policy/v1"` is true, it will print out `policy/v1` otherwise it will print out  `policy/v1beta1`

What problem are you getting when you install this?

**Comment by caleblloyd** [comment]
Closing for now due to more info needed
