### ISSUE TITLE
[nats helm 1.x] nats-server pid location changes based on configuration

### ISSUE THREAD

**Issue by mprimi** [nats-io/k8s#759]
Using Helm chart `nats-1.0.0-beta6`

With:
```
  reloader:
    enabled: false
```
The `nats-server` pid file is found at: `/var/run/nats.pid`

With:
```
  reloader:
    enabled: true
```
The `nats-server` pid file is found at a different location: `/var/run/nats/nats.pid`

**Comment by caleblloyd** [comment]
This is by design.  When the reloaded is enabled, the PID file needs to be accessible by both the `nats` and `reloader` containers.

When the `reloader` is enabled, an `emptyDir` volume is created at `/var/run/nats` and mounted to both containers, and the PID file is written inside of that volume

When the `reloader` is disabled, this volume does not exit, and the `/var/run/nats` directory does not exist, so the pidfile goes in `/var/run` instead.

0.x may have always been making this volume. But it is not necessary to make when the reloader is not enabled so 1.x changes to only make the volume if it is needed.

**Comment by caleblloyd** [comment]
Ah, I had not considered the unprivileged use case.  Seems that it is best to always make the `emptyDir` then - #782
